## This manifest deploys a Job which performs one time
# configuration of Calico
apiVersion: batch/v1
kind: Job
metadata:
  name: configure-calico-bgp-peer2
  namespace: kube-system
  labels:
    k8s-app: calico-bgp
spec:
  template:
    metadata:
      name: configure-calico-bgp
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
        scheduler.alpha.kubernetes.io/tolerations: |
          [{"key": "dedicated", "value": "master", "effect": "NoSchedule" },
           {"key":"CriticalAddonsOnly", "operator":"Exists"}]
    spec:
      hostNetwork: true
      restartPolicy: OnFailure
      containers:
        # Writes basic configuration to datastore.
        - name: configure-calico-bgp
          image: calico-bgp/ctl:v1.0.2
          args:
          - apply
          - -f
          - /etc/config/calico-bgp/calico-peer2.yaml
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
      volumes:
       - name: config-volume
         configMap:
           name: calico-bgp-config
           items:
            - key: calico-peer.yaml
              path: calico-bgp/calico-peer2.yaml